### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by PercyJames** [Eltrut-Co/Flamboyant-Refabricated#6]
ok so, when I added this mod to a pack to make non-Euclidian spaces I crash on startup. 

Crash report: https://pastebin.com/x1B7E27n

mod list:

fabric-api-0.35.1+1.16
flamboyant_refabricated-1.16.5-1.0.0
immersive-portals-0.90-mc1.16.5-fabric
invisiblights-fabric-6.0
Pehkui-2.2.1+1.14.4-1.17
worldedit-mod-7.2.5-dist

**Comment by PercyJames** [comment]
it doesn't launch at all

**Comment by Steven-Baez** [comment]
oh sorry you need autoconfig

**Comment by Steven-Baez** [comment]
@PercyJames

**Comment by PercyJames** [comment]
oh thanks!

**Comment by Steven-Baez** [comment]
np!
